spring.application.name=week1
debug = true

notif.type = email
# Concept 13:
# notif.type = sms set in env variable takes precedence.
# => achieved loosely coupled system design! We don't have to change the code at compile time.